title: Booker Martin
logo: "/images/logo.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! Welcome to Booker Martin's online portfolio.
  <br><br>
  1060 Los Altos Ave, Los Altos, CA 94022
  <br><br>
  bookerjmartin@gmail.com
  <br><br>
  (650) 722-9773
  <br><br>
  <a href="https://www.linkedin.com/in/bookerm/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
